### ISSUE TITLE
The arrays of ASE Atoms object are destroyed

### ISSUE THREAD

**Issue by superstar54** [superstar54/beautiful-atoms#101]
After building a Batoms object from an ASE Atoms object, the arrays of the ASE Atoms object are destroyed.

Here is a example:
```python
from batoms import Batoms
atoms = molecule("H2O")
h2o = Batoms("h2o", from_ase = atoms)
print(atoms)
Traceback (most recent call last):
  File "<blender_console>", line 1, in <module>
  File "/home/xing/apps/blender-3.0.0-linux-x64/3.0/python/lib/python3.9/site-packages/ase/atoms.py", line 989, in __repr__
    N = len(self)
  File "/home/xing/apps/blender-3.0.0-linux-x64/3.0/python/lib/python3.9/site-packages/ase/atoms.py", line 959, in __len__
    return len(self.arrays['positions'])
KeyError: 'positions'
```

This is because that `pop` function is used when reading ASE data.

**Comment by superstar54** [comment]
This has been fixed.
